site_name: queue_worker
site_description: queue worker for sync and async function
site_author: jiamo

repo_url: https://github.com/jiamo/queue_worker
edit_uri: https://github.com/jiamo/queue_worker/edit/master/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributing: about/contributing.md
    - License: about/license.md
